version: '3.4'

services:
  simpleapi:
    image: ${DOCKER_REGISTRY-}simpleapi
    build:
      context: .
      dockerfile: SimpleAPI/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - caddy
      - seq

  seq:
    image: datalust/seq:latest

  caddy:
    image: caddy:2.7-alpine

    restart: unless-stopped
    ports:
      - "5002:5002"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config 
  
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data 
    environment:
      - POSTGRES_PASSWORD=password123 # would be replaced on normal deployment
      - POSTGRES_USER=sa

  grafana:
    image: grafana/grafana:7.5.7
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  caddy_data:
  caddy_config:
  pgdata:
  app-seq:
    external: false
  grafana-data:
    external: false

